CC = gcc
CXX = g++
CFLAGS = -O3 -Wall `pkg-config --cflags opencv4` -Iinclude
BUILD_DIR = build/video_creator

OBJS = $(BUILD_DIR)/timeline.o \
       $(BUILD_DIR)/video_creator.o

TARGET = generate-video

$(TARGET): $(OBJS)
	@mkdir -p $(BUILD_DIR)
	$(CXX) $(CFLAGS) `pkg-config --libs opencv4` -o $@ $^

$(BUILD_DIR)/%.o: %.cpp
	@mkdir -p $(BUILD_DIR)
	$(CXX) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(BUILD_DIR) $(TARGET)
