CC = gcc
CXX = g++
CFLAGS = -g -O0 -Wall `sdl2-config --cflags`
SRC_DIR = src
BUILD_DIR = build/timeline_display

OBJS = $(BUILD_DIR)/timeline.o \
       $(BUILD_DIR)/timeline_display.o

TARGET = $(BUILD_DIR)/app

$(TARGET): $(OBJS)
	@mkdir -p $(BUILD_DIR)
	$(CXX) $(CFLAGS) `sdl2-config --cflags --libs` -o $@ $^

$(BUILD_DIR)/%.o: %.cpp
	@mkdir -p $(BUILD_DIR)
	$(CXX) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(BUILD_DIR)
